### ISSUE TITLE
3.3?

### ISSUE THREAD

**Issue by cheerfulstoic** [neo4j/docker-neo4j#106]
Is the 3.3.0 docker image on the way?

I also notice that 3.2.6 isn't on Docker Hub yet either

**Comment by adamrothman** [comment]
Bump – changes in 3.3 look great, can't wait to try them.

**Comment by adamrothman** [comment]
Anybody out there? Looks like the source is already checked in here and just needs to be published?

**Comment by DFoxinator** [comment]
It would be great to see 3.3 released on Docker Hub.

**Comment by DFoxinator** [comment]
@spacecowboy any ETA on this?

**Comment by spacecowboy** [comment]
Due to changes related to the commercial license for 3.3 we are a bit behind on publishing this. It will be published once we have resolved a few critical issues

**Comment by ryguyrg** [comment]
This is now available!  https://hub.docker.com/_/neo4j/

Note: you now have to set another environment variable on enterprise to indicate your agreement with the license.  

Example:
```
docker run --env=NEO4J_ACCEPT_LICENSE_AGREEMENT=yes neo4j:3.3.0-enterprise 
```

**Comment by cheerfulstoic** [comment]
Thanks Ryan!

**Comment by DFoxinator** [comment]
Awesome, thanks!
