### ISSUE TITLE
Neo4j 3.0.0-alpha image

### ISSUE THREAD

**Issue by FylmTM** [neo4j/docker-neo4j#11]
I am wondering if it is possible to add 3.3.0 alpha image?

Currently I changed all my manual Neo4j installations with docker images.
Only 3.0.0 is left. 

I am using 3.0.0 locally, to develop against that version and my project. 
So, adding 3.0.0 image for me will be:
- Easy Neo4j 3.0.0-alpha installation
- Easy upgrade
- I will be cool developer with docker containers

**Comment by benbc** [comment]
Hello @FylmTM. I'm afraid that we're not able to make a 3.0.0 image available yet. We will be releasing an official milestone before long and that will be available as a Docker image.
