### ISSUE TITLE
Possibility to specify single configuration files

### ISSUE THREAD

**Issue by FylmTM** [neo4j/docker-neo4j#12]
Currently there is possibility to specify some of most-used configuration via `--env` variables.
Also, we can specify `conf/` as volume. 

I am using different Neo4j versions locally (2.2.6, 2.3.0, 3.0.0). Env variables is OK for me.
But I want to additionally configure Neo4j logging, by providing just single configuration file.

Mouting `conf/` will force me to handle all configuration, for all version separately, because configuration may differ from version-to=version.

**Comment by benbc** [comment]
Hi @FylmTM. Can you let me know what logging configuration you want to change and why?

**Comment by FylmTM** [comment]
@benbc I am writing different unmanaged extensions. Usually I end up with adjusting logging configuration, to get specific debug output.

**Comment by benbc** [comment]
@FylmTM Yes, that would be a good improvement.

We can just copy the contents of `/conf` over `/var/lib/neo4j/conf` instead of removing the latter altogether.

I won't be able to do this immediately, however.

**Comment by FylmTM** [comment]
@benbc Copying will be good enough solution for me!

**Comment by benbc** [comment]
This is implemented in https://github.com/neo4j/docker-neo4j/commit/026fcee712c5fd2596c7d41e14c2981404d94df2.
