### ISSUE TITLE
Browser interface consumes massive CPU

### ISSUE THREAD

**Issue by smackesey** [neo4j/docker-neo4j#121]
I have a Neo4j Docker container running locally that has been configured as follows:

```sh
$ docker run \
--name=neo4j.stmpd \
--publish=7475:7474 \
--publish=7688:7687 \
--volume=/Users/smackesey/stm/neo4j:/data \
--env=NEO4J_dbms_active__database=stmpd \
--env=NEO4J_dbms_allow__upgrade=true \
--env=NEO4J_dbms_security_auth__enabled=false \
neo4j
```

There seems to be a problem with the browser interface -- it seems to take up almost all of my machine's CPU. The interface is usable but somewhat sluggish. CPU appears to be consumed even when queries are not being processed. In the log (viewed through Docker Kitematic), this error is repeatedly printed, with everything the same except for the timestamp and reference code:

```
2018-01-25 18:39:12.310+0000 ERROR Client triggered an unexpected error [UnknownError]: Network channel towards /172.17.0.1:54684 is closed. Client has probably been stopped., reference 8942aabe-2662-484f-b117-91e90b23a07e.
```

If I close the browser tab with the Neo4j browser, the CPU demand goes back to normal within 10 seconds or so.

**Comment by smackesey** [comment]
This problem turned out to be due to a massive number of unused indexes that I created while running tests. The indexes were on labels that were not used (anymore) on any node in the database. When I deleted the indexes the browser functioned normally again. Probably still something worth looking into as the behavior seems unexpected even with the unused indexes.

**Comment by oskarhane** [comment]
Thanks for getting back to us!
We have noted this and will look into it.
