### ISSUE TITLE
Failed to `make` to community image -  403 Forbidden

### ISSUE THREAD

**Issue by lag-linaro** [neo4j/docker-neo4j#138]
$ cp devenv.local.template devenv.local
$ sed -i 's/<the-version-you-want-to-test-against>/3.5/' devenv.local
$ cat devenv.local
# -*- mode: shell-script -*-

NEO4J_VERSION=3.5
$ . devenv
$ make
mkdir -p in
cd in
curl --fail --silent --show-error --location --remote-name http://dist.neo4j.org/neo4j-community-3.5-unix.tar.gz
curl: (22) The requested URL returned error: 403 Forbidden
Makefile:114: recipe for target 'in/neo4j-community-3.5-unix.tar.gz' failed
make: *** [in/neo4j-community-3.5-unix.tar.gz] Error 22

**Comment by jennyowen** [comment]
You have to put the patch number into the `NEO4J_VERSION` variable.
So for example:
`export NEO4J_VERSION=3.5.2`
`make clean test`
