### ISSUE TITLE
Neo4j docker image start up

### ISSUE THREAD

**Issue by pandadumpling** [neo4j/docker-neo4j#144]
This issue is more in terms of documentation available around noe4j - docker images. 
Business Scenario: Up the neo4j app(not run it). Create the database(.db file) and then start neo4j to use the new .db file.
Issue: We couldn't find any documentation or helpful posts around. We ended up opening neo4j image and tweaking it to meet our requirements. I don't think so this is a one off business scenario and could be a common issue.

**Comment by jennyowen** [comment]
We're working on improving the docker documentation.
You can find what we have here:
https://neo4j.com/docs/operations-manual/current/docker/
