### ISSUE TITLE
Neo4J: command failed: initial password was not set because live Neo4j-users

### ISSUE THREAD

**Issue by glserran** [neo4j/docker-neo4j#148]
Hi,

I have experienced this issue. I get this error when trying to deploy docker-neo4j latest version. I managed to make it work by changing the following:
```

diff --git a/3.4.6/community/docker-entrypoint.sh b/3.4.6/community/docker-entrypoint.sh
index df500af..e7c45ba 100755
--- a/3.4.6/community/docker-entrypoint.sh
+++ b/3.4.6/community/docker-entrypoint.sh
@@ -173,7 +173,8 @@ if [ "${cmd}" == "neo4j" ]; then
             exit 1
         fi
         # Will exit with error if users already exist (and print a message explaining that)
-        bin/neo4j-admin set-initial-password "${password}" || true
+        rm /data/dbms/auth -f
+       bin/neo4j-admin set-initial-password "${password}" || true
     elif [ -n "${NEO4J_AUTH:-}" ]; then
         echo >&2 "Invalid value for NEO4J_AUTH: '${NEO4J_AUTH}'"
         exit 1

```

This is as suggested in here: 

https://stackoverflow.com/questions/47530154/neo4j-command-failed-initial-password-was-not-set-because-live-neo4j-users-wer

I am not sure if this is totally wrong but at least it works.

**Comment by jennyowen** [comment]
hi @glserran thanks for reporting the issue! It should be fixed in the latest Neo4j docker images.
