### ISSUE TITLE
Mounting via --volume fails

### ISSUE THREAD

**Issue by ekkis** [neo4j/docker-neo4j#15]
I'm running Neo from a Docker container like this:

`docker run -d -p 7474:7474 --name neo --env NEO4J_NO_AUTH=true --volume /Applications/neo4j-community-2.2.5/data:/data neo4j/neo4j`

where the /Applications path contains my existing database (I have Neo installed locally and it uses that path).  if I attach to the container and take a look, there's a database there:

`docker exec -it neo /bin/bash`
`ls /data/graph.db`

but running a query `match (n) return n` at the `/browser` comes back empty.  I'm running on OSX Yosemite.  any thoughts?

**Comment by ekkis** [comment]
ok.  figured it out.  the home page here:

https://hub.docker.com/r/neo4j/neo4j/

indicates that I can mount volumes in the way I did.  however, what it doesn't say is that on OSX, the Docker daemon runs within a VM *and therefore* the path given points to *that VM's* filesystem.  I have learned however, that the VM automatically maps the /Users directory to the hosting system, thus placing my graph.db directory within that tree will work.  do keep in mind however that:

`cd ~/data`
`docker run --volume .:/data`

won't work because the reference is not to the local filesystem but to the VM's, thus:

`cd ~/data`
`docker run --volume ~/data:/data`

will work.  I'm leaving this issue open so the maintainers of that site fix the page to add this information for us OSX users

**Comment by benbc** [comment]
@ekkis I'm glad you worked that out. Since this is a standard Docker-on-OSX thing, rather than specific to the Neo4j image, I'd rather not add it to the image docs. We're trying to keep those docs as simple and comprehensible as possible and it's going to be a struggle to do that as we add more behaviour to the image.

**Comment by benbc** [comment]
I've now added some general advice about OSX to the README: https://github.com/neo4j/docker-neo4j/commit/24259da41e1c6ca88f5e6cdd44146b5d810c156c.
