### ISSUE TITLE
Configure ssl certificate and key path via environment variables

### ISSUE THREAD

**Issue by iesen** [neo4j/docker-neo4j#17]
It would be perfect if we set these properties in neo4j-server.properties using environment variables.

**Comment by benbc** [comment]
@iesen That's a great idea, thanks. We'll try to get it in soon.

**Comment by srbaker** [comment]
We have added the ability to provide SSL certificate and key in https://github.com/neo4j/docker-neo4j/commit/01d3407f0bf75da399e47bad58ec7704dc6e95a2 .

If you provide the key and certificate, and name them appropriately, they will get used automatically.
