### ISSUE TITLE
Why does /ssl need to be writeable?

### ISSUE THREAD

**Issue by netgio** [neo4j/docker-neo4j#174]
In this commit https://github.com/neo4j/docker-neo4j/commit/768b1a9e005451eaaf720cf96db43821b0a8ec32 @jennyowen uncommented code in docker_entrypoint.sh that checks whether a number of directories are writable. 

The check on /ssl in particular breaks my secure deployment to Azure Container Instances using secret volumes.  Secret volumes are read-only, the test fails and the container terminates.

Is there any reason why /ssl should be writeable to successfully launch the container?

**Comment by jennyowen** [comment]
@netgio that check was supposed to be opt-in: https://github.com/neo4j/docker-neo4j/blob/master/src/3.5/docker-entrypoint.sh#L231

but it looks like the version of `docker-entrypoint.sh` that got published to dockerhub wasn't the correct commit: https://github.com/neo4j/docker-neo4j-publish/blob/master/3.5.6/community/docker-entrypoint.sh#L226

I think I messed up the release somewhere. (cc @anlutro you were right!)

To the question of whether `/ssl` actually needs to be *writable*, I'm not sure. Perhaps readability is enough. I'll check before re-releasing the correct version to dockerhub. 
If this is blocking your work, you can use the `3.5.5` image.

**Comment by jennyowen** [comment]
The fix will be on dockerhub when (if?) this is accepted:
https://github.com/docker-library/official-images/pull/6118

**Comment by jennyowen** [comment]
@netgio This should now be fixed, please could you try again and report back?

**Comment by netgio** [comment]
Confirmed - no longer checks for writability of /ssl.  Deployment to Azure Container Instances with SSL via Secret Volumes is working again.  Thanks

**Comment by jennyowen** [comment]
Brilliant, thanks for confirming!
