### ISSUE TITLE
How NEO4J_ALLOW_STORE_UPGRADE should be used ?

### ISSUE THREAD

**Issue by sgrunt91** [neo4j/docker-neo4j#21]
Hi,

I'm trying to migrate my Neo4j to Docker container.
All seems to work quite good, exept when I want to use my current database.

The database is not on the same Neo4j version than the Docker Image, so I need "allow_store_upgrade" set to true in neo4j.properties.

I've tried to use NEO4J_ALLOW_STORE_UPGRADE environment variable like this:
> docker run --name=neo4j-test --detach --publish=7474:7474 --env=NEO4J_ALLOW_STORE_UPGRADE=true --volume=/mydata/neo4j-data/:/data  --ulimit=nofile=40000:40000 neo4j

or

> docker run --name=neo4j-test --detach --publish=7474:7474 --env=NEO4J_ALLOW_STORE_UPGRADE='true' --volume=/mydata/neo4j-data/:/data --ulimit=nofile=40000:40000 neo4j

But when I'm copying my graph.db content and start the container I still have this error:
>  # docker logs neo4j-test
Starting Neo4j Server console-mode...
2015-12-23 12:20:23.146+0000 INFO  No SSL certificate found, generating a self-signed certificate..
2015-12-23 12:20:24.633+0000 INFO  Successfully shutdown Neo4j Server
2015-12-23 12:20:24.635+0000 ERROR Neo4j cannot be started, because the database files require upgrading and upgrades are disabled in configuration. Please set 'allow_store_upgrade' to 'true' in your configuration file and try again.

I've tried to do a "dump-config" to a config folder and the varialble is still on comment: 
> /conf# grep allow_store_upgrade neo4j.properties
#allow_store_upgrade=true

Is there a bug in the docker image, or am I the bug ? 

Regards,

**Comment by benbc** [comment]
Hello @sgrunt91. I'm sorry you're having trouble with this.

The `NEO4J_ALLOW_STORE_UPGRADE` feature is not yet available for the `neo4j` image in the official image library. It's only available in the image in our own repo on Docker Hub (i.e. `neo4j/neo4j`).

Are you able to use that instead?

The feature will be part of the next release to the official image library (2.3.2), but we don't have a date for that yet.

**Comment by sgrunt91** [comment]
Hello @benbc ,

Oh :( Well, I'm too hasty, I'll wait for it!

For now I change my container with using neo4j/neo4j:2.2.7 which is my actual database version, so no need to use this variable.
I wanted to benefit from the docker migration to do a Neo4j version upgrade, but I can wait.
There are another environnement variables that not available yet ?

I guess it shows, I'm new to docker, and I hadn't understand the difference between official library and your repo, for me `neo4j` was the same that `neo4j/neo4j`, but if I understand `neo4j` is the release of a last `neo4j/neo4j` ? so there a delta between them.
I'm confused.

So, I think you could close this if you want. My bad...

Thanks again!
Regards,

**Comment by benbc** [comment]
You'll see that the documentation for the official image (`neo4j`, [here](https://hub.docker.com/_/neo4j/)) and the image in our repo (`neo4j/neo4j`, [here](https://hub.docker.com/r/neo4j/neo4j/)) is identical except for this one feature, so it's understandable that you were confused.

If you're on 2.2.7 then you'll need to get that from `neo4j/neo4j` anyway. When you get round to upgrading to 2.3.1, you'll find that `NEO4J_ALLOW_STORE_UPGRADE` works fine if you use `neo4j/neo4j`; and if 2.3.2 is out by the time you upgrade then it'll work for `neo4j` too.
