### ISSUE TITLE
docker-compose: starting Neo4j as non-root user

### ISSUE THREAD

**Issue by mcolburn** [neo4j/docker-neo4j#242]
[Neo4j documentation](https://neo4j.com/docs/operations-manual/current/docker/introduction/) describes how to run a docker container with neo4j as non-root, but it does not state how to do this with docker-compose.  How can this be done?

**Comment by jennyowen** [comment]
You can check the docker compose documentation to find out how to convert `docker run` commands into compose files, here:

https://docs.docker.com/compose/compose-file/#domainname-hostname-ipc-mac_address-privileged-read_only-shm_size-stdin_open-tty-user-working_dir

 For the `--user` flag you should add a `user: <VALUE>` parameter under your neo4j service.

Here's an example of a neo4j compose file used for some tests (it has some variables that need replacing so won't work without modification, but you can see how it specifies a non-root user):
https://github.com/neo4j/docker-neo4j/blob/master/src/test/resources/causal-cluster-compose.yml
