### ISSUE TITLE
neo4j-browser  connect to server with wrong address

### ISSUE THREAD

**Issue by WestFarmer** [neo4j/docker-neo4j#248]
version: 4.05

running with on a remote host:
```
docker run \
>     --publish=7474:7474 --publish=7687:7687 \
>     --volume=$HOME/neo4j/data:/data \
>     neo4j
```
neo4j-browser can login in with initial username/password, but execute any Cypher statement will fail:
`e6906fea-5fd6-4ca4-a329-43f60195291c:16 WebSocket connection to 'ws://0.0.0.0:7687/' failed: Connection closed before receiving a handshake response`

**Comment by jennyowen** [comment]
I think this is the same issue as #240
Does it work if you start neo4j like this? 
```
docker run -it --rm \
    --publish=7474:7474 --publish=7687:7687 \
	-e NEO4J_dbms_connector_https_advertised__address=":7473" \
	-e NEO4J_dbms_connector_http_advertised__address=":7474" \
	-e NEO4J_dbms_connector_bolt_advertised__address=":7687" \
    neo4j
```

**Comment by jennyowen** [comment]
Since there was no reply I'm going to assume my suggestion worked and this was the same underlying issue as #240 .
Neo4j 4.0.4 has been released and has the fix for the networking problem.
