### ISSUE TITLE
Set uid explicitly

### ISSUE THREAD

**Issue by StianOvrevage** [neo4j/docker-neo4j#252]
To use AzureFile with Neo4j on Kubernetes you seem to need to do a static assignment of the neo4j uid on a custom StorageClass. (Ref https://community.neo4j.com/t/cant-seem-to-mount-volume-with-neo4j-3-3-9-path-in-use/9889/4 )

In the example it uses uid 100, but I see in the image I use (3.5.17) the uid has changed to 101. Highlighting the problem with this tight coupling to something not explicitly set.

Can you update the Dockerfile to ensure that the creation of neo4j user always results in a known uid that we can rely on to be stable in the future?

**Comment by jennyowen** [comment]
@StianOvrevage this seems reasonable, although I'm not sure what effect it might have on other users. 
I've made the change to our source. The new UID and GID will both be 7474.

**Comment by jennyowen** [comment]
This has been added since Neo4j 4.1.1 and will be in 4.0.7 onwards (for the Neo4j 4.0 series).
UID and GID are both set to 7474 in the image.
