### ISSUE TITLE
s390x support for neo4j

### ISSUE THREAD

**Issue by sangitanalkar** [neo4j/docker-neo4j#268]
Neo4j [binary](https://neo4j.com/download/) works fine on s390x machine. Wanted to know if docker image too can be provided for s390x arch.
Thanks

**Comment by jennyowen** [comment]
It's nice that neo4j works on s390x architectures but we do *absolutely no testing* for it, so we can't guarantee the quality or usability of any docker images we would provide. 
We only recently started providing unsupported images for arm64, and I made the same arguments on that issue too.
https://github.com/neo4j/docker-neo4j/issues/140

There are no plans to support s390x architecture now or in the forseeable future (at least, that I am aware of). Plus we're dependent on openjdk images, which also doesn't provide s390x.

I could make it easier to generate images based on different architectures though. Currently it requires a bit of work to convert dependencies over, and that could be scripted somehow.

**Comment by sangitanalkar** [comment]
Hi @jennyowen 
I came across s390x image for neo4j at [link](https://hub.docker.com/r/s390x/neo4j) which is a very old image and is not working for s390x. So was thinking whether we could get image for latest version of the same.
Also, just an update, for openjdk image we can refer to image at [link](https://hub.docker.com/_/openjdk?tab=tags&page=1&name=11-jre-slim-stretch) which is supported for both s390x as well as amd64

**Comment by sangitanalkar** [comment]
Closing this issue for now as community does not have any plans to support s390x. 
I'll be happy to assist the community to add s390x support if planned in future. Thanks!
