### ISSUE TITLE
experimental newer builds fail on arm64v8 with platform incompatibility error msg

### ISSUE THREAD

**Issue by drahnreb** [neo4j/docker-neo4j#286]
Build process seems to be wrong for docker hub on [neo4j/neo4j-arm64-experimental](https://hub.docker.com/r/neo4j/neo4j-arm64-experimental)

- **Steps to reproduce**: 
```bash
$ docker run \
    --publish=7474:7474 --publish=7687:7687 \
    --volume=$HOME/neo4j/data:/data \
    --volume=$HOME/neo4j/logs:/logs \
    neo4j/neo4j-arm64-experimental:4.1.6-arm64
```
- The output of the `docker version` command
```bash
$ sudo docker version
Client: Docker Engine - Community
 Version:           20.10.3
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        48d30b5
 Built:             Fri Jan 29 14:33:47 2021
 OS/Arch:           linux/arm64
 Context:           default
 Experimental:      true
 
Server: Docker Engine - Community
 Engine:
  Version:          20.10.3
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       46229ca
  Built:            Fri Jan 29 14:32:03 2021
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
- Operating system: (for example Windows 95/Ubuntu 16.04)
`Ubuntu 20.04.1 ARM64. 5.8.0-41-generic`

- Additionally, include (as appropriate) log-files, stacktraces, and other debug output.
```bash
WARNING: The requested image’s platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

standard_init_linux.go:219: exec user process  caused: no such file or directory
```

**Comment by jennyowen** [comment]
oh yes that does seem to be very broken. Thanks for reporting it.
I found a bug in the Makefiles which was preventing ARM64 images from being built properly, and I've pushed a fix.

Re-releasing everything will be non-trivial to fix, but you could build your own ARM images by cloning this repository and doing:
```
NEO4JVERSION=4.1.6 make -f make-arm64.mk package-arm
```
(assuming you still want to build version 4.1.6 and not something more recent).

**Comment by drahnreb** [comment]
Thanks for the quick fix. Works, tested with neo4j/docker-neo4j@b2b7720 and `NEO4JVERSION=4.2.3`.

**Comment by jennyowen** [comment]
I've updated the ARM64 images on dockerhub, so they should work again.
