### ISSUE TITLE
neo4j-shell support

### ISSUE THREAD

**Issue by ekkis** [neo4j/docker-neo4j#29]
at present the Dockerfile doesn't export port 1337, which is used by the neo4j-shell utility.  this makes it impossible to load a database via scripts since the utility is refused connection.

could we add that port number to the export list?  is there anything else that's needed for that to work?

**Comment by benbc** [comment]
Hello @ekkis. This is a good idea -- we'll try to get it in soon. In the meantime, are you able to use `docker exec --interactive <container> bin/neo4j-shell` as a workaround?

**Comment by ekkis** [comment]
there are other workarounds but I would like to see this implemented

**Comment by benbc** [comment]
@ekkis I'm sorry, but this isn't possible without changing the way the Neo4j shell itself works. I see that you've been discussing this on StackOverflow and I'm afraid that we don't have any clever answers here.

Are you able to use [cycli](https://github.com/nicolewhite/cycli), an alternative shell that uses the standard Neo4j APIs?

**Comment by ekkis** [comment]
I haven't looked at cycli but I'll take a look.  why isn't it as simple as opening the port?

**Comment by benbc** [comment]
Because the Neo4j Shell uses RMI as a transport. By default RMI negotiates a connection over the configured port (1337 in this case) and then opens an arbitrary high port for the actual communication; we can't know ahead of time what that port is, so we can't instruct Docker to open it.

**Comment by ekkis** [comment]
makes sense.  pity that.
