### ISSUE TITLE
Neo4j - Unable to run multiple cypher files with Neo4J Docker 4.2.5

### ISSUE THREAD

**Issue by akshaymhetre** [neo4j/docker-neo4j#290]
I am using neo4j with docker version 4.2.5 and cypher file to initialize data.

I am setting following environment property to initialize data with docker-compose -

NEO4J_apoc_initializer_cypher=CALL apoc.cypher.runFile ("file:///sample.cypher")

This works fine and load the data after server started. However, you cannot create indexes in this file. You need runSchema call to create indexes. As per doc for neo4j 4.2, you can run multiple cypher,

NEO4J_apoc_initializer_cypher_0=CALL apoc.cypher.runSchemaFile ("file:///schema.cypher")

NEO4J_apoc_initializer_cypher_1=CALL apoc.cypher.runFile ("file:///sample.cypher")

However, this throws error:

unknown settings: apoc.initilizer.cypher.0

unknown settings: apoc.initilizer.cypher.1

**Comment by jennyowen** [comment]
@jexp is this an issue with apoc or cypher perhaps?

**Comment by akshaymhetre** [comment]
@jennyowen i think this seems neo4j.conf couldn't understand these properties. But as per doc it should.

**Comment by jennyowen** [comment]
@akshaymhetre do you mean this documentation? https://neo4j.com/labs/apoc/4.2/operational/init-script/

This says the parameter is `apoc.initializer.<DATABASENAME>.0` you're creating parameters `apoc.initialize.cypher.0` so you're doing `initialize` not `initializer` and is your database called `cypher` or are you using the default database name `neo4j`?

**Comment by akshaymhetre** [comment]
Apologies, Some copying error from my side, i have updated the issue. 
I am using initializer in the code and also using different database other than neo4j and system.
As i mentioned it worked with single file but not working with multiple ones.

**Comment by akshaymhetre** [comment]
@jennyowen  Tried with apoc.initializer.<DATABASENAME>.0 as well still not working
Same error has been thrown:
Unrecognized setting. No declared setting with name: apoc.initializer.mydb.0

**Comment by aowss** [comment]
I have the same problem

**Comment by jennyowen** [comment]
It sounds like neo4j is starting up and the parameters are being correctly passed. I believe this is a problem with APOC rather than the docker image.
Could you raise your issue at https://github.com/neo4j-contrib/neo4j-apoc-procedures please?

**Comment by aowss** [comment]
@akshaymhetre Do you want to raise an issue on the APOC side ?

**Comment by akshaymhetre** [comment]
@aowss added [at](https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/2120), Please add your points if any.
