### ISSUE TITLE
Question - alpine to debian

### ISSUE THREAD

**Issue by asethia** [neo4j/docker-neo4j#298]
Hi,

I can see  between 3.x to 4.x docker image; the docker image is moved from alpine to debian. Any particular reason for that.

Thanks
Arun

**Comment by jennyowen** [comment]
It was because OpenJDK on alpine was found to be mystery pre-release versions of java and is not an officially supported openjdk version as a result.

> The OpenJDK port for Alpine is not in a supported release by OpenJDK, since it is not in the mainline code base. [source](https://hub.docker.com/_/openjdk)

There's a more in depth discussion of the topic here:
https://github.com/docker-library/openjdk/issues/320
