### ISSUE TITLE
Unable to load GDS and APOC plugins in docker container

### ISSUE THREAD

**Issue by jprashant21** [neo4j/docker-neo4j#300]
**Docker-compose:**

version: '3.7'

services:
  neo4j:
    image: neo4j:4.2.3-enterprise
    container_name: "neo-gds1.5"
    volumes:
      - $HOME/graph_data/my_data:/data
      - $HOME/graph_data/my_data:/var/lib/neo4j/import
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_AUTH=neo4j/1234
      - NEO4JLABS_PLUGINS=["apoc", "graph-data-science"]
      - apoc.import.file.enabled=true
    networks:
      - neo_net

**Error logs:**
WARNING: Max 1024 open files allowed, minimum of 40000 recommended. See the Neo4j manual.
Changed password for user 'neo4j'.
Fetching versions.json for Plugin 'apoc' from https://neo4j-contrib.github.io/neo4j-apoc-procedures/versions.json
Error: No jar URL found for version '4.2.3' in versions.json from 'https://neo4j-contrib.github.io/neo4j-apoc-procedures/versions.json'

**Comment by jennyowen** [comment]
I tried reproducing your error but the apoc (and graph data science) plugin loaded as expected:

```
docker run -it --rm \
-e NEO4JLABS_PLUGINS='["apoc", "graph-data-science"]' \
-e NEO4J_AUTH=none \
-e  apoc.import.file.enabled=true \
-e NEO4J_ACCEPT_LICENSE_AGREEMENT=yes \
neo4j:4.2.3-enterprise

Fetching versions.json for Plugin 'apoc' from https://neo4j-contrib.github.io/neo4j-apoc-procedures/versions.json
Installing Plugin 'apoc' from https://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/download/4.2.0.4/apoc-4.2.0.4-all.jar to /var/lib/neo4j/plugins/apoc.jar 
```

Maybe try clearing your docker image cache and try again?

Also, unrelated but Neo4j isn't going to recognise your `apoc.import.file.enabled=true` configuration parameter. You need to convert it to the environment variable format, as described here:

https://neo4j.com/docs/operations-manual/current/docker/configuration/#docker-environment-variables

**Comment by jprashant21** [comment]
I tried again after clearing all previous containers and images related to neo4j. But, i run into same error again. Could it be related to proxy issue that jar file is not reachable for download?

[prashant@my-laptop]> docker run -it --rm \
> -e NEO4JLABS_PLUGINS='["apoc", "graph-data-science"]' \
> -e NEO4J_AUTH=none \
> -e  apoc.import.file.enabled=true \
> -e NEO4J_ACCEPT_LICENSE_AGREEMENT=yes \
> neo4j:4.2.3-enterprise
Unable to find image 'neo4j:4.2.3-enterprise' locally
4.2.3-enterprise: Pulling from library/neo4j
69692152171a: Already exists 
ce2b89b60818: Pull complete 
6584437267ff: Pull complete 
2a57595b940f: Pull complete 
9d7310023fbb: Pull complete 
adba7b3ef632: Pull complete 
e0610d289b20: Pull complete 
d3a5cb529b8a: Pull complete 
Digest: sha256:2c6d32d89864a13e6781a0db04aa75dd7be1ee03b10390547083db18b63371ee
Status: Downloaded newer image for neo4j:4.2.3-enterprise
Fetching versions.json for Plugin 'apoc' from https://neo4j-contrib.github.io/neo4j-apoc-procedures/versions.json
Error: No jar URL found for version '4.2.3' in versions.json from 'https://neo4j-contrib.github.io/neo4j-apoc-procedures/versions.json'

**Comment by jennyowen** [comment]
yeah, a proxy or firewall would be my next guess. Are you able to go to https://neo4j-contrib.github.io/neo4j-apoc-procedures/versions.json in your browser? What about: https://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/download/4.2.0.4/apoc-4.2.0.4-all.jar ?

**Comment by jprashant21** [comment]
yes, I can access both the links in my browser. I downloaded the jar manually. Is it possible to just upload this jar file in host /plugins directory and neo4j can read it from there?
Also, I didnt see any message for downloading GDS plugin? Is it downloaded in the background or something?

**Comment by jprashant21** [comment]
Its working now...I downloaded the jar manually and uploaded this jar file to host /plugins volume...thanks for your help !!

**Comment by jennyowen** [comment]
no problem!

**Comment by studyVersion** [comment]
is there a problem with the gds library on docker containers using windowns? i put the exat same command on linux : docker run --name testneo4j -p 7474:7474 -p 7687:7687 -v /path/to/neo4j/data:/data -e NEO4J_AUTH=neo4j/12345678 --env NEO4J_PLUGINS='["graph-data-science"]' -d neo4j:latest
 and with the return gds.version() i get it's up and running, but on windows 11,  not a chance!! this is the error message i get : Unknown function 'gds.version' (line 1, column 8 (offset: 7))
"EXPLAIN return gds.version()"
