### ISSUE TITLE
Failed to connect to web interface with conf in volume

### ISSUE THREAD

**Issue by toddleo** [neo4j/docker-neo4j#31]
Hi, I was trying to start the official docker image, with provided conf dir via volume, like the following:

```
docker run --rm --publish=7474:7474 --volume=${DB_DIR}:/data/graph.db --volume=${CONF_DIR}:/conf neo4j
```

and from the printed log, everything seems to be working:

```
Starting Neo4j Server console-mode...
2016-03-30 11:49:03.208+0000 INFO  No SSL certificate found, generating a self-signed certificate..
2016-03-30 11:49:09.060+0000 INFO  Successfully started database
2016-03-30 11:49:09.118+0000 INFO  Starting HTTP on port 7474 (8 threads available)
2016-03-30 11:49:09.470+0000 INFO  Enabling HTTPS on port 7473
2016-03-30 11:49:09.613+0000 INFO  Mounting static content at /webadmin
2016-03-30 11:49:09.702+0000 INFO  Mounting static content at /browser
2016-03-30 11:49:11.400+0000 INFO  Remote interface ready and available at http://localhost:7474/
```

however, the 7474 port can't be reached, and `curl` results failure:

```
$ curl 127.0.0.1:7474
curl: (56) Recv failure: Connection reset by peer
```

I thought there should be something wrong with my configurations, hence I dumped a set of configurations from the docker image and retried, except getting the same failure above.

Once I removed `volume=${CONF_DIR}:/conf` from my `docker run` command, the web interface runs smoothly. And the log is same to the case which fails.

Anyone happens to know where I did it wrong? Could really use your help. Thanks.

**Comment by spacecowboy** [comment]
@toddleo I would guess that there is a problem with your configuration files in `${CONF_DIR}`. Could you post their contents?

**Comment by toddleo** [comment]
Also checked `data/log` dir, no `console.log`, `neo4j.?.?.log` or `wrapper.log` as described in `data/log/README.txt`.

As for `graph.db/messages.log`, no WARN was found. I could post some here, if it's relevant.

**Comment by benbc** [comment]
@toddleo Thanks for reporting this. Can you give me a bit more information, please? What versions of Docker and Neo4j are you using? What platform are you running on?

**Comment by toddleo** [comment]
@benbc Hi Ben,

I'm using the neo4j docker image [from docker hub](https://hub.docker.com/r/neo4j/neo4j/), which I believe it is still the latest. Image ID: 7d94602c724e .

My docker version is `Docker version 1.10.3, build 20f81dd`.

Should I also try the [Official Neo4j Image for Production Use](https://hub.docker.com/_/neo4j/)?

**Comment by benbc** [comment]
Hello @toddleo. We recommend using the image from the official library, but it's basically identical to the one in `neo4j/neo4j`, so it won't fix your problem.

What platform are you running on?

**Comment by toddleo** [comment]
Ahhh forgot to attach my environment. We are running docker on Gentoo 2.2, with `4.0.5-gentoo-ks` kernel.

**Comment by benbc** [comment]
@toddleo Please could I ask you to try the same thing but without mounting the `/conf` volume, so that we can rule out the possibility of config problems?

```
docker run --rm --publish=7474:7474 --volume=${DB_DIR}:/data/graph.db neo4j
```

**Comment by toddleo** [comment]
@benbc Hi Ben,

I did what you said, except with `--publish=7478:7474` since my friends are currently using that port hosting the other neo4j container. 

In this case, 7478 port can be well reached by `curl`.

**Comment by benbc** [comment]
Thanks, @toddleo. Could you run this, please?

```
docker run --volume=/tmp/conf:/conf neo4j dump-config
diff /tmp/conf ${CONF_DIR}
```

**Comment by toddleo** [comment]
@benbc Hi Ben,

Absolutely, the `diff` command prints the following:

```
diff /tmp/conf ${CONF_DIR}
diff /tmp/conf/neo4j-server.properties /home/users/liulx/dk/dm-graph/cs-it/conf.d/neo4j-server.properties
68c68
< org.neo4j.server.http.log.enabled=false
---
> org.neo4j.server.http.log.enabled=true
```

It is worth to point out that the only difference on `log.enabled` is exactly what I changed to see what's going on with the http server, after I discovered this issue.

Apologies for this late reply.

**Comment by toddleo** [comment]
Turns out you have to uncomment this, before using custom conf files, even the content is exactly the same:

```
# To have HTTP accept non-local connections, uncomment this line
dbms.connector.http.address=0.0.0.0:7474
```

**Comment by benbc** [comment]
@toddleo You are quite right, I should have thought of that. Well spotted. We'll add something to the docs about this.

**Comment by toddleo** [comment]
@benbc Hi Ben, 

I reckon it's better off allow non-local connections by default when using docker, or at least add an environment variable when starting docker container: 

```
--env=NEO4J_dbms_connector_http_address=0.0.0.0:7474
```

**Comment by jmwnoble** [comment]
Could a line be added to the documentation, section 2.5.4.2. /conf volume indicating that this needs to be uncommented:
# To accept non-local connections, uncomment this line:
dbms.connectors.default_listen_address=0.0.0.0

Will save people time if they have this issue, which I bumped into today

**Comment by spacecowboy** [comment]
we'll do that @jmwnoble

**Comment by jjaderberg** [comment]
@jmwnoble a note to that effect has been added and will be published in a few days or so
