### ISSUE TITLE
Docker entry point config doesnt allow for fabric configs

### ISSUE THREAD

**Issue by bwinchester** [neo4j/docker-neo4j#312]
https://github.com/neo4j/docker-neo4j/blob/81a2edb9ea9cddfdcb7fbc6a8750b7f2671ee471/docker-image-src/4.4/docker-entrypoint.sh#L265

Seeing the validation logic in the Environment replace logic for the docker entrypoint, I figured out why our testing pipeline couldn't configure fabric for tests using environment variables. The Entrypoint validates config settings using the config file, and therefore cant validate any fabric configs for specific fabric graphs.

I know 4.4.0 is slated to dynamically allow for fabric configuration, but will you support this in the docker entrypoint as well?

CI pipelines are a great example for this workflow.

**Comment by jennyowen** [comment]
I'll look into it.
Meanwhile, you're in luck because we just published an alpha version of 4.4 so you can also test for yourself if 4.4 does what you need. That's at:
* `neo4j/neo4j-experimental:4.4.0-alpha01`
* `neo4j/neo4j-experimental:4.4.0-alpha01-enterprise`

**Comment by bwinchester** [comment]
Hi all. I was able to test the alpha release of 4.4 with the new docker config. Fabric name and fabric graph configs are working and the db is starting with the configuration from env vars!
