### ISSUE TITLE
Edited

### ISSUE THREAD

**Issue by EarthlingDavey** [neo4j/docker-neo4j#313]
Edited

**Comment by jennyowen** [comment]
Yep, https://hub.docker.com/_/neo4j?tab=description is legit :+1: 
The bot that updates it is owned by docker, not us, so I don't really know why it's in a weird order there.

Thanks for taking the time to reach out to us to report it though! That would have been bad if our docker account was really compromised.

**Comment by EarthlingDavey** [comment]
ok awesome! Thanks for letting me know.

IDK if you have a contact at docker who's open to feedback. IMHO the username doijanky as the official image publisher was one of the things that didn't look quite right. A google search for doijanky doesn't really clarify anything. The bot's profile links through to a Jenkins dashboard https://doi-janky.infosiftr.net - and as this isn't on the docker domain I mistakenly thought it could potentially be malicious. 

I suspect there might be other docker users that might follow the same thought process. So it may be worth considering a change.

Anyways, cheers! Thanks for your work at neo4j :) Have a good Friday.
