### ISSUE TITLE
Stuck downloading the image!

### ISSUE THREAD

**Issue by Mahmoudz** [neo4j/docker-neo4j#33]
Tried to pull the images 10 times during the day and it keep stopping! (happened for both versions `neo4j:2.3` and `neo4j:3.0`)

<img width="886" alt="screen shot 2016-05-20 at 8 46 44 pm" src="https://cloud.githubusercontent.com/assets/1983984/15436839/7a137926-1ecc-11e6-8245-e9ce1a085cd1.png">

Here's all my code: https://github.com/LaraDock/laradock/commit/5c9eb97db5adef1057ce7bb77dd9fc0a0cd7e529

**Comment by benbc** [comment]
@Mahmoudz That sounds like it might have been a problem with Docker Hub. Serving up images from the official library is completely out of our control. Can you see if you can reproduce it?

**Comment by Mahmoudz** [comment]
@benbc tried it again now and still stuck there.
