### ISSUE TITLE
Can't disable authorization

### ISSUE THREAD

**Issue by BalmungSan** [neo4j/docker-neo4j#358]
- **Steps to reproduce**

Just running any `4.4.x` version with the `NEO4J_AUTH` env var set as `none`; e.g.

```
docker run -d --publish=7474:7474 --publish=7687:7687 --env=NEO4J_AUTH='none​' --name neo4j neo4j:4.4.9
```

- Expected behaviour

The container starts without authentication.

- Actual behaviour

The container does not starts, and logs the following error:

> none​ is invalid
> Invalid value for NEO4J_AUTH: 'none​'

- Neo4j image tag being used, eg `neo4j:latest`, `neo4j:enterprise-3.5` etc

Any `4.4.x` community image appears to be affected, but I personally tested with `latest`, `4.4.9`, `4.4.8` & `4.4.7`

- The output of the `docker version` command

```
Client: Docker Engine - Community
 Cloud integration: v1.0.24
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.17.11
 Git commit:        100c701
 Built:             Mon Jun  6 23:03:17 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Desktop
 Engine:
  Version:          20.10.17
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.11
  Git commit:       a89b842
  Built:            Mon Jun  6 23:01:23 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.6
  GitCommit:        10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc:
  Version:          1.1.2
  GitCommit:        v1.1.2-0-ga916309
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

- Operating system: (for example Windows 95/Ubuntu 16.04)

Ubuntu 20.04 on WSL 2 on Windows 10

-----

Maybe this is related to the change of the base docker image?

_PS: Also, the `4.4.9` image is actually running the `4.4.8` version of **Neo4j**_

**Comment by jennyowen** [comment]
When I pasted your command into a terminal it added some weird extra characters:

```
docker run -it --rm \
--publish=7474:7474 \
--publish=7687:7687 \
--env=NEO4J_AUTH='none<200b>' neo4j:4.4.8
```
and gave the same error message you reported. The extra characters didn't show up in a text editor.

When I re-wrote the `'none'` it worked as expected. You can even set it as `--env=NEO4J_AUTH=none` to avoid the single quotes.

I think this might be some weird whitespace or character encoding that's crept into your code and is causing problems (maybe through copy and pasting from different sources?).  If you just re-type the `--env=NEO4J_AUTH=none` by hand it should work.

Also thanks for reporting 4.4.9 community being the wrong version. It looks like I made a typo in the release, I've submitted a PR to docker to fix it.
