### ISSUE TITLE
Update base image due to openjdk deprecation

### ISSUE THREAD

**Issue by jdsbanares** [neo4j/docker-neo4j#375]
- **Steps to reproduce**
N/A

- Expected behaviour
N/A

- Actual behaviour
N/A

- Neo4j image tag being used
neo4j@sha256:592de9343cf46d17193518b533beda2841e3f3c5ec59a28213352750f90e84af
neo4j:4.4.10-enterprise

- The output of the `docker version` command
N/A

- Operating system: (for example Windows 95/Ubuntu 16.04)
N/A

Hi all, the openjdk image is being deprecated (https://github.com/docker-library/openjdk/issues/505). The base image for the docker neo4j build should also probably be updated.

Is there already work being done for this?

Thanks!

**Comment by jennyowen** [comment]
The 4.4.10 image doesn't use openjdk, it uses `debian:bullseye-slim` + `eclipse-temurin`.

**Comment by jennyowen** [comment]
More generally, this was fixed in all neo4j images released since they announced the deprecation: 
https://github.com/neo4j/docker-neo4j/pull/353

This is the exact Dockerfile 4.4.10-enterprise is running:
https://github.com/neo4j/docker-neo4j-publish/blob/master/4.4.10/enterprise/Dockerfile
