### ISSUE TITLE
neo4j An critical error occurred

### ISSUE THREAD

**Issue by liyin37** [neo4j/docker-neo4j#378]
## Guidelines

Please note that GitHub issues are only meant for bug reports/feature requests. 
If you have questions on how to use Neo4j, please ask on [Neo4j Community](https://community.neo4j.com/) or [StackOverflow](http://stackoverflow.com/questions/tagged/neo4j) instead of creating an issue here.

To help us understand your issue, please specify important details, primarily:

- **Steps to reproduce**. *Not including reproduction steps will mean your bug will take considerably longer to investigate and fix. Please don't skip this*.
- Expected behaviour
- Actual behaviour
- Neo4j image tag being used, eg `neo4j:latest`, `neo4j:enterprise-3.5` etc
- The output of the `docker version` command
- Operating system: (for example Windows 95/Ubuntu 16.04)

Additionally, include (as appropriate) error messages, log-files, stacktraces, and other debug output.

when I run neo4j in k8s ，the yaml below
···
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: neo4j
  name: neo4j
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neo4j
  serviceName: neo4j-headless
  template:
    metadata:
      labels:
        app: neo4j
    spec:
      containers:
      - env:
        - name: NEO4J_AUTH
          value: neo4j/xxxxxxxxxxx
        - name: NEO4J_dbms_memory_heap_max__size
          value: 512m
        - name: NEO4J_dbms_memory_pagecache_size
          value: 512M
        - name: TZ
          value: Asia/Shanghai
        image: neo4j:4.4.2-apoc
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 10
          initialDelaySeconds: 300
          periodSeconds: 20
          successThreshold: 1
          tcpSocket:
            port: 7474
          timeoutSeconds: 20
        name: neo4j
        ports:
        - containerPort: 7474
          name: http
          protocol: TCP
        - containerPort: 7687
          name: api
          protocol: TCP
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: "1"
            memory: 2Gi
        volumeMounts:
        - mountPath: /data
          name: data
        - mountPath: /etc/localtime
          name: localtime
      initContainers:
      - command:
        - sh
        - -c
        - if [ -e /data/lost+found ];then rm /data/lost+found -rf;fi
        image: neo4j:4.4.2-apoc
        imagePullPolicy: IfNotPresent
        name: initdata
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /data
          name: data
      volumes:
      - hostPath:
          path: /usr/share/zoneinfo/Asia/Shanghai
          type: ""
        name: localtime
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      labels:
        app: neo4j
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 100Gi
      storageClassName: nfs-storage

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: neo4j
  name: neo4j
spec:
  ports:
  - name: http
    port: 7474
    protocol: TCP
    targetPort: 7474
  - name: api
    port: 7687
    protocol: TCP
    targetPort: 7687
  selector:
    app: neo4j
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: neo4j
  name: neo4j-headless
spec:
  clusterIP: None
  ports:
  - name: http
    port: 7474
    protocol: TCP
    targetPort: 7474
  - name: api
    port: 7687
    protocol: TCP
    targetPort: 7687
  selector:
    app: neo4j
  type: ClusterIP

···
run few times，the pod found error
![image](https://user-images.githubusercontent.com/42507175/188802034-c5db522f-4257-4760-a1f4-b1da0075d1b3.png)

**Comment by jennyowen** [comment]
I don't know what the `neo4j:4.4.2-apoc` image is, but it is not something we have created or support, and isn't even on Dockerhub.
I suggest you follow up with whoever provided you with that image.

**Comment by sirReeall** [comment]
@liyin37 That error looks to be related to the the dbms rather than an issue with docker. Have a look at your debug.log and trace the issue there
