### ISSUE TITLE
403 for https://graphdatascience.ninja/versions.json

### ISSUE THREAD

**Issue by KonstantinKlepikov** [neo4j/docker-neo4j#386]
I know, i know where is a problem - `curl https://graphdatascience.ninja/versions.json` from Russia return 403 because is hosts on AWS, and AWS blocks this country. Ok, there is no politics - we know why amazon make it, we have what we have.

apparently versions.json is used for manage plugins like graph-data-science in neo4j container. It is possible create an mirror for this source?

thanks anyway

**Comment by MishaDemianenko** [comment]
Lol. Oh no, how that happened? who would have thought
You have what you have

**Comment by KonstantinKlepikov** [comment]
@MishaDemianenko however, and this is important, an exception can be made for the community license. Not all people support what is happening, but for now, “have what you have” remains. These are free developers, researchers, students and other small people, and they are left alone with the big task of discovering knowledge. Give them a chance to advance
