### ISSUE TITLE
Latest tag is set to Neo4j 5.1

### ISSUE THREAD

**Issue by james-m-hall** [neo4j/docker-neo4j#389]
The `latest` tag on the official Neo4j  docker image seems to have been set to version 5.1 of Neo4j (see https://hub.docker.com/_/neo4j/tags).

This is a bit unexpected because as far as I can work out Neo4j 5.x is still pre-release, see for example https://neo4j.com/release-notes/ which says at time of writing that "The most current release of Neo4j is 4.4.12". The documentation [here](https://neo4j.com/docs/operations-manual/current/docker/) also seems to be focused on Neo4j 4.4 without even an option to select documentation for 5.x

Can the `latest` tag be reverted back to a released version of Neo4j?

**Comment by jennyowen** [comment]
@james-m-hall 5.1.0 is released today. It was up on docker a little early because a docker release takes about 24hrs.
