### ISSUE TITLE
Changed password for user 'neo4j'. IMPORTANT: this change will only take effect if performed before the database is started for the first time.

### ISSUE THREAD

**Issue by ZhangY18** [neo4j/docker-neo4j#392]
## Guidelines
Error will be reported when starting after each shutdown
Changed password for user 'neo4j'. IMPORTANT: this change will only take effect if performed before the database is started for the first time.

docker run -d -p 7474:7474 -p 7687:7687 
-v E:/Docker/data/neo4j/data:/data 
-v E:/Docker/data/neo4j/logs:/logs 
-v E:/Docker/data/neo4j/conf:/var/lib/neo4j/conf 
-v E:/Docker/data/neo4j/import:/var/lib/neo4j/import 
--env NEO4J_AUTH=neo4j/123456 --name neo4j neo4j

**Comment by jennyowen** [comment]
Yes? What's the problem exactly?

**Comment by sirReeall** [comment]
@ZhangY18 This is expected as if you start a stopped container which uses some persisted storage, or start a container that was previously started and not removed, then `NEO4J_AUTH` has no effect. 

The message is not an error it is informative.
