### ISSUE TITLE
Missing neo4j docker image version 4.3.20

### ISSUE THREAD

**Issue by oren-nonamesecurity** [neo4j/docker-neo4j#401]
Neo4j 4.3.20 was released 4 days ago:
https://neo4j.com/release-notes/database/neo4j-4-3-20/

But docker tag wasn't pushed to DockerHub:
https://hub.docker.com/_/neo4j/tags

**Comment by jennyowen** [comment]
I tend to group releases together if I know a few are coming out at the same time, to reduce noise for our friends in the docker repository.
I've requested a new dockerhub release for 4.3.20 and 4.4.13 here:
https://github.com/docker-library/official-images/pull/13487

**Comment by vikingUnet** [comment]
Thanks!

**Comment by oren-nonamesecurity** [comment]
Hi, 
Looks like the new tags uploaded yesterday are still discovered as vulnerable to Text4Shell - 
https://hub.docker.com/_/neo4j/tags

Any idea why? The release notes mentioned update common-text version 1.9 to 1.10 to solve this CVE.

**Comment by vikingUnet** [comment]
Hello! Yes, it is because it contains apos neo4j plugin, that use commons-text version 1.9, not 1.10. Developers od apos plugin still approving PR for remake import commons-text lib only on neo4j runtime; docker images neo4j must including new version of neo4j-apos 4.0.9, not 4.0.8 (at it is now)
