### ISSUE TITLE
NEO4J_DEBUG env variable not working anymore ? 

### ISSUE THREAD

**Issue by ikwattro** [neo4j/docker-neo4j#403]
I have the following very simple compose : 

```yaml
version: '3'
services:
  neo4j:
    image: neo4j:5.1.0-enterprise
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      NEO4J_DEBUG: "yes"
      NEO4J_AUTH: neo4j/password
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
```

However, the expected result is that the entrypoint script would start logging in debug mode, however Neo4j doesn't start and throw the following exception : 

```
$ docker compose logs --tail 100 -f neo4j
03-simple-compose-neo4j-1  | Failed to read config /var/lib/neo4j/conf/neo4j.conf: Unrecognized setting. No declared setting with name: DEBUG. Cleanup the config or disable 'server.config.strict_validation.enabled' to continue.
03-simple-compose-neo4j-1  | Run with '--verbose' for a more detailed error message.
```

**Comment by jennyowen** [comment]
@ikwattro the `NEO4J_DEBUG` option is in the source code here, but was added after the 5.1.0 release, so is not in the 5.1.0 docker images.
The exact source code that is running in the `neo4j:5.1.0-enterprise` image is:
https://github.com/neo4j/docker-neo4j-publish/blob/master/5.1.0/enterprise/local-package/docker-entrypoint.sh

Your compose should work for 5.2.0-enterprise when it's released, which should be within the next few days.

**Comment by ikwattro** [comment]
Thanks @jennyowen , seems I was living on the edge :) , looking forward to 5.2

**Comment by jennyowen** [comment]
5.2.0 available soon: https://github.com/docker-library/official-images/pull/13574
