### ISSUE TITLE
neo4j-admin v5 Docker images are not available

### ISSUE THREAD

**Issue by tekrei** [neo4j/docker-neo4j#404]
It seems neo4j-admin v5 images are not yet available in the Docker hub: https://hub.docker.com/r/neo4j/neo4j-admin

Is there any information about when or how these images would be available?

Because we couldn't perform Docker maintenance properly without these images.

**Comment by jennyowen** [comment]
@tekrei thank you for reporting that. I've pushed the 5.1.0 admin images to dockerhub now.
