### ISSUE TITLE
neo4j-admin:5.10.0 not released on Docker Hub

### ISSUE THREAD

**Issue by ikwattro** [neo4j/docker-neo4j#456]
Hi,

I realised that the `neo4j-admin` image is not published on the Dockerhub ( as well as 5.11 ). Is it discontinued ?

**Comment by jennyowen** [comment]
Thanks for reporting this!
The neo4j-admin images are not discontinued there were just some problems in our release pipeline. 5.10 and 5.11 admin images are now available with a dazziling range of tags.

**Comment by ikwattro** [comment]
Thanks @jennyowen !
