### ISSUE TITLE
Limit Memory usage with docker

### ISSUE THREAD

**Issue by sauravskumar** [neo4j/docker-neo4j#47]
Is there any way to limit neo4j memory usage when running inside a docker container? I have a server with 2gb ram but most of it is used by neo4j, 800MB to be exact and there are a lot of other containers running which need more free memory. Please help.

**Comment by benbc** [comment]
Hello @sauravskumar. You can constrain Neo4j's memory usage by setting environment variables. For 2.3 they are `NEO4J_CACHE_MEMORY` and `NEO4J_HEAP_MEMORY` (see [docs](https://neo4j.com/developer/docker-2.x/#_neo4j_configuration) for details); for 3.0 they are `NEO4J_dbms_memory_pagecache_size` and `NEO4J_dbms_memory_heap_maxSize` (see [docs](https://neo4j.com/developer/docker-3.x/#_neo4j_configuration) for details).

Please reopen this issue if that doesn't solve your problem.

**Comment by sauravskumar** [comment]
@benbc Thank You!
