### ISSUE TITLE
neo4j-admin:5.20.0 not released on Docker Hub

### ISSUE THREAD

**Issue by bruno00o** [neo4j/docker-neo4j#501]
Hi,

Contrary to the instructions given on the page [https://neo4j.com/docs/operations-manual/current/docker/dump-load/](https://neo4j.com/docs/operations-manual/current/docker/dump-load/), `neo4j-admin:5.20.0` is not available on Docker Hub. Should I use an older version?

**Comment by jennyowen** [comment]
hi @bruno00o thanks for reporting this. 
I've uploaded the 5.20 neo4j-admin images to dockerhub now so you should be good to go.
