### ISSUE TITLE
Error when dumping database neo4j-admin Docker

### ISSUE THREAD

**Issue by bruno00o** [neo4j/docker-neo4j#502]
Hi,

Using `neo4j-admin`, I encountered an error when trying to dump my database.

## Steps to reproduce

1. Stop the neo4j Docker container.
2. Run `neo4j-admin` as [this page](https://neo4j.com/docs/operations-manual/current/docker/dump-load/) describes it.

```
docker run --interactive --tty --rm \
   --volume=./data:/data \
   --volume=./backups:/backups \
   neo4j/neo4j-admin:latest \
neo4j-admin database dump neo4j --to-path=/backups
```

## Error encountered

```
INFO  [o.n.c.d.DumpCommand] Starting dump of database 'neo4j'
ERROR [o.n.c.d.DumpCommand] Failed to dump database 'neo4j': Failure when checking for recovery state: '%s'.java.lang.IllegalArgumentException: Unknown serialization format version: 0
ERROR [o.n.c.d.DumpCommand] Dump failed for databases: 'neo4j'
Dump failed for databases: 'neo4j'
```

## Environment

- Ubuntu 20.04.6 LTS
- Docker version 26.1.3
- neo4j 5.20.0

**Comment by jennyowen** [comment]
@bruno00o does this work again now that you can use neo4j-admin 5.20?

**Comment by bruno00o** [comment]
yes! it is working with `neo4j-admin:5.20`, thank you @jennyowen
