### ISSUE TITLE
5.24.2 : "no matching manifest for linux/amd64 in the manifest list entries"

### ISSUE THREAD

**Issue by ilgrosso** [neo4j/docker-neo4j#521]
```
$ docker pull neo4j:5.24.2
5.24.2: Pulling from library/neo4j
no matching manifest for linux/amd64 in the manifest list entries
```

**Comment by jennyowen** [comment]
This is generally caused by slowness in dockerhub infrastructure updating, and usually fixes itself after a while.
If you're still having trouble, please raise the issue with docker here: https://github.com/docker-library/official-images/pull/17725
