### ISSUE TITLE
Improve documentation of image (password + link to neo4j docker documentation)

### ISSUE THREAD

**Issue by callicles** [neo4j/docker-neo4j#61]
The neo4j image is able to change the password of the neo4j user on start up. The syntax is not very clear from the README docker documentation.

@spacecowboy mentioned on docker-library/docs#719 that there is [this documentation](http://neo4j.com/docs/operations-manual/current/deployment/single-instance/docker/) Would be nice to have the link to there in the README. 
(I had no idea that page existed)

**Comment by spacecowboy** [comment]
@callicles thanks for bringing it up here.

Just to make sure we are talking about the same things, the README does link to that page under *Documentation* at https://hub.docker.com/_/neo4j/:

![selection_023](https://cloud.githubusercontent.com/assets/223655/19431715/d8ff1c08-9459-11e6-8738-f3796566b38b.png)

If that IS the page you are talking about, would you consider it a fix if this link was easier to find in that wall of text?

**Comment by callicles** [comment]
Interesting, I was not looking through dockerhub but through the store https://store.docker.com/images/5f0be9a7-f5d7-4974-9c0e-78c33484e79c.
On that page there are broken links that are supposed to point to the documentation.

<img width="501" alt="screen shot 2016-10-17 at 12 31 36 pm" src="https://cloud.githubusercontent.com/assets/4429209/19446219/c4b62122-9465-11e6-8457-b5c06a520694.png">

![screen shot 2016-10-17 at 12 32 42 pm](https://cloud.githubusercontent.com/assets/4429209/19446229/d20bd2c2-9465-11e6-9389-52d4ceb70501.png)

**Comment by benbc** [comment]
Oh! That store page must be built from an out-of-date Docker hub page. Maybe it is a Docker problem after all. I'll take this back to them. Thanks for reporting this.

**Comment by spacecowboy** [comment]
@callicles the store page has now been updated to match the docker hub page:
https://store.docker.com/images/5f0be9a7-f5d7-4974-9c0e-78c33484e79c
