### ISSUE TITLE
3.1?

### ISSUE THREAD

**Issue by Joshfindit** [neo4j/docker-neo4j#69]
Haven't used the Docker container before, but went to pull 3.1, and it's not available?

**Comment by benbc** [comment]
Hello @Joshfindit. Neo4j 3.1 is not GA yet and we don't publish our milestones to the official library. You can get it instead from the `neo4j-experimental` repo on Docker Hub (for example `docker pull neo4j-experimentl/3.1.0-M13-beta3`).

**Comment by Joshfindit** [comment]
Ahh, that makes perfect sense. Thanks for adding the details of how to get it.

**Comment by mneedham** [comment]
@Joshfindit I wrote up an example of using the experimental version in case it's useful - http://www.markhneedham.com/blog/2016/11/13/neo4j-3-1-beta3-docker-creating-a-causal-cluster/
