### ISSUE TITLE
Different directory for SSL certificates in Docker volume argument and settings.

### ISSUE THREAD

**Issue by dhimmel** [neo4j/docker-neo4j#74]
The [3.1 operations manual](http://neo4j.com/docs/operations-manual/3.1/installation/docker/#docker-encryption) provides the following command to provide your own certificate to a Docker container:

```
docker run --publish 7473:7473 --publish=7687:7687 --volume $HOME/neo4j/ssl:/ssl neo4j:3.1
```

However, the default [`dbms.directories.certificates`](https://neo4j.com/docs/operations-manual/3.1/reference/configuration-settings/#config_dbms.directories.certificates) is `certificates`.

So shouldn't the Docker command use ` --volume $HOME/neo4j/ssl:/var/lib/neo4j/certificates`, or is something else going on? Does changing `dbms.directories.certificates` in your `Dockerfile` have any effect?

**Comment by spacecowboy** [comment]
Short answer: you can use either but not both

You can see what's going on here: https://github.com/neo4j/docker-neo4j/blob/master/src/3.1/docker-entrypoint.sh#L63

```bash
if [ -d /ssl ]; then
    setting "dbms.directories.certificates" "/ssl" neo4j.conf
fi
```

If you mount a `/ssl` directory, then that will take precedence.

However if you don't, then you are free to mount your certs directly in `/var/lib/neo4j/certificates`.

You can even mount them anywhere you like but then you'd have to provide a volume with a custom configuration file as well.

Hope that answers your question

**Comment by dhimmel** [comment]
Thanks @spacecowboy. Makes sense and seeing `docker-entrypoint.sh` helped clear things up.
