### ISSUE TITLE
`tools/` not in the image?

### ISSUE THREAD

**Issue by Joshfindit** [neo4j/docker-neo4j#82]
Looking for recovery tools such as `tools/src/main/java/org/neo4j/tools/dump/LenientInvalidLogEntryHandler.java` and `/tools/src/main/java/org/neo4j/tools/rebuild/RebuildFromLogs.java`

**Comment by spacecowboy** [comment]
As far as I know, they aren't shipped in any of our packaged products (`tar.gz`, `.deb`, `.rpm`). Docker is "just another form of packaging".

**Comment by Joshfindit** [comment]
That makes sense. Is there a recommended way to get them?

**Comment by spacecowboy** [comment]
If think the only way is to download the source and compiling it yourself. These tools aren't typically intended for general customer use which is why they are exposed in convenient ways.
