### ISSUE TITLE
Image 3.1.3 not starting

### ISSUE THREAD

**Issue by sylvainroussy** [neo4j/docker-neo4j#84]
Hi,

For information purpose, I had an issue with Neo4j community docker image  3.1.3 : not starting (data from 3.1.0, Apoc and MySQl in plugins folder). No issue in 3.1.0 :

```
Caused by: java.lang.ClassNotFoundException: org.neo4j.kernel.api.proc.Mode
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 20 more
```

My docker-compose :

```
neo4j:
  image: "neo4j:3.1.3"
  restart: always
  ports:
    - 7474:7474
    - 7687:7687
  volumes:
    - /DATA/neo4j/data/:/data
    - /DATA/neo4j/conf:/var/lib/neo4j/conf
    - /DATA/neo4j/plugins:/var/lib/neo4j/plugins
    - /DATA/neo4j/logs:/var/lib/neo4j/logs
```
Docker version: 17.04.0-ce build 4845c56
Ubuntu: 16.04.2 LTS

**Comment by spacecowboy** [comment]
@sylvainroussy it's almost certainly an issue with Apoc. Try again without the `plugings` volume. It it works correctly then it's an apoc issue. If Apoc doesn't compile against the particular version of neo4j then neo4j can't start.

**Comment by sylvainroussy** [comment]
After checking your comment, you're right.

Thanks, closing.

**Comment by spacecowboy** [comment]
Just FYI, there is work ongoing to improve the visibility of these kinds of errors related to plugins. Ideally, soon you'll get a message that tells you that a plugin is incompatible and just a generic java exception
