### ISSUE TITLE
Can't connect to bolt port when using docker swarm

### ISSUE THREAD

**Issue by AndreSteenbergen** [neo4j/docker-neo4j#88]
Using a simple docker service create command:

 `docker service create --constraint node.role==manager --name neo4j --network mynetwork --mount type=volume,src=Neo4jData,target=/data neo4j:3.1.0`

I get this error when trying to connect to the bolt port, using the c# bolt driver:
`Neo4j.Driver.V1.ClientException: Failed to connect to the server neo4j:7687 within connection timeout 5000ms`

I can't seem to get it to work. Does anyone have a suggestion. Running it on plain docker on 1 server, no problem. It just works...

**Comment by spacecowboy** [comment]
How are you connected to it? From within the docker network or from your localhost?

If from localhost, you need to bind the bolt port to your local machine (same as for local docker execution).

**Comment by AndreSteenbergen** [comment]
I am trying to connect from the docker network.
the dotnet service I start using another docker service create, with the same network.

**Comment by spacecowboy** [comment]
ok. without more details on how you are connecting I can't say much else. It would be helpful (and probably necessary) for you to provide a reproducible example.

**Comment by AndreSteenbergen** [comment]
Will do, won't be today, is there a command line method of testing the bolt protocol?

**Comment by spacecowboy** [comment]
just download cypher-shell: https://github.com/neo4j/cypher-shell/releases/tag/1.1.0

**Comment by AndreSteenbergen** [comment]
My bad, I was running on an alternative port ...
