### ISSUE TITLE
WebSocket connection to 'ws://localhost:7687/' failed 

### ISSUE THREAD

**Issue by thobalose** [neo4j/docker-neo4j#93]
I recently hit  [WebSocket connection to 'ws://localhost:7687/' failed ](https://github.com/neo4j/neo4j-browser/issues/522) and tried disabling all connectors (bolt and https) but http. Looking for help...

**Comment by Antman261** [comment]
I'm also having this issue.

**Comment by spacecowboy** [comment]
@thobalose you say in the issue that you have disabled bolt. The current version of the neo4j browser ONLY supports bolt.

**Comment by thobalose** [comment]
@spacecowboy Thank you for the reply.

Kindly help me with the following:

- Having the ability to [disable bolt](https://neo4j.com/docs/operations-manual/current/configuration/connectors/#_additional_options_for_neo4j_connectors) on the neo4j.conf file has no effect? 

- Is it no longer possilble to run neo4j on a single port?

**Comment by spacecowboy** [comment]
@thobalose 

* disabling bolt in the config file is fine but then you can't use the browser because the browser will only connect over bolt in 3.2.
* it is perfectly possible to run neo4j on a single http port (and no bolt) but you can't use the browser then

**Comment by thobalose** [comment]
@spacecowboy 

How can I run Neo4j 3.2.1 with an older version of the Neo4j-browser (that has `Do not use Bolt`) and what are the disadvantages?

**Comment by spacecowboy** [comment]
@thobalose you can't

why don't you want bolt enabled?

**Comment by thobalose** [comment]
I had worked on integrating Neo4j as an interactive environment on the [Galaxy] (https://galaxyproject.org/) platform. I wanted to update the version we had integrated but it currently supports a single docker port.

Thank you for the help @spacecowboy

**Comment by spacecowboy** [comment]
ok. Closing the issue then since it's not a docker issue. hope you can solve your integration somehow.
